BSData_mainmenu:
        pattern:  /
        defaults: { _controller: BSDataBundle:Default:index }


BSData_menu:
     pattern:  /data
     defaults: { _controller: BSDataBundle:Default:data }

BSData_product_show:
        pattern:  /data/product/show/{id}
        defaults: { _controller: BSDataBundle:Product:show }

BSData_product_edit:
        pattern:  /data/product/edit/{id}
        defaults: { _controller: BSDataBundle:Product:edit }

BSData_product_new:
        pattern:  /data/product/new
        defaults: { _controller: BSDataBundle:Product:new }

BSData_product_create:
        pattern:  /data/product/create
        defaults: { _controller: BSDataBundle:Product:create }

BSData_product_delete:
        pattern:  /data/product/delete/{id}
        defaults: { _controller: BSDataBundle:Product:delete }

BSData_product_update:
        pattern:  /data/product/delete/{id}
        defaults: { _controller: BSDataBundle:Product:delete }

BSData_product:
    pattern:  /data/product/{page}
    defaults: { _controller: BSDataBundle:Product:index,page: 1 }






BSData_stock_show:
        pattern:  /data/stock/show/{id}
        defaults: { _controller: BSDataBundle:stock:show }

BSData_stock_edit:
        pattern:  /data/stock/edit/{id}
        defaults: { _controller: BSDataBundle:stock:edit }

BSData_stock_new:
        pattern:  /data/stock/new
        defaults: { _controller: BSDataBundle:stock:new }

BSData_stock_create:
        pattern:  /data/stock/create
        defaults: { _controller: BSDataBundle:stock:create }

BSData_stock_delete:
        pattern:  /data/stock/delete/{id}
        defaults: { _controller: BSDataBundle:stock:delete }

BSData_stock_update:
        pattern:  /data/stock/update/{id}
        defaults: { _controller: BSDataBundle:stock:update }

BSData_stock:
    pattern:  /data/stock/{page}
    defaults: { _controller: BSDataBundle:stock:index,page: 1 }



BSData_plant_show:
        pattern:  /data/plant/show/{id}
        defaults: { _controller: BSDataBundle:plant:show }

BSData_plant_edit:
        pattern:  /data/plant/edit/{id}
        defaults: { _controller: BSDataBundle:plant:edit }

BSData_plant_new:
        pattern:  /data/plant/new
        defaults: { _controller: BSDataBundle:plant:new }

BSData_plant_create:
        pattern:  /data/plant/create
        defaults: { _controller: BSDataBundle:plant:create }

BSData_plant_delete:
        pattern:  /data/plant/delete/{id}
        defaults: { _controller: BSDataBundle:plant:delete }

BSData_plant_update:
        pattern:  /data/plant/update/{id}
        defaults: { _controller: BSDataBundle:plant:update }

BSData_plant:
    pattern:  /data/plant/{page}
    defaults: { _controller: BSDataBundle:plant:index,page: 1 }








