<?php

namespace Acme\BSCheckoutBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * checkoutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class checkoutRepository extends EntityRepository
{

    public function getCurrentBasket($cashbox_id){

        $em = $this->getEntityManager();
        $qb = $this->createQueryBuilder('b');
        $qb->where('b.finish <> true');
        $qb->andWhere('b.cashbox ='.$cashbox_id);
        try{
            $result = $qb->getQuery()->setMaxResults(1)->getSingleResult();
        } catch (\Doctrine\Orm\NoResultException $e) {
            $result = null;
        }


        if(!$result){
            $result = new Checkout();
            $result->setBuydate(new \DateTime());
            $result->setCashbox($cashbox_id);
            $result->setFinish(false);
            $result->setSummary(0);
            $result->setPayment(0);
            $this->getEntityManager()->persist($result);
            $this->getEntityManager()->flush();
        }
        return $result;
    }

    public function clearCurrentBasket($cashbox_id){

        $em = $this->getEntityManager();
        $qb = $this->createQueryBuilder('b');
        $qb->where('b.finish <> true');
        $qb->andWhere('b.cashbox ='.$cashbox_id);
        try{
            $cb = $qb->getQuery()->setMaxResults(1)->getSingleResult();
        } catch (\Doctrine\Orm\NoResultException $e) {
            $cb = null;
        }

        foreach($cb->getCheckoutItems() as $item){
            $em->remove($item);

        }

        $em->flush();
        return $cb;
    }

}