
BSOrder_menu:
    pattern:  /orders
    defaults: { _controller: BSOrderBundle:Default:index }


BSOrder_search:
    pattern:  /orders/search
    defaults: { _controller: BSOrderBundle:Default:index }

BSOrder_invoice:
    pattern:  /orders/invoice
    defaults: { _controller: BSOrderBundle:Default:invoice }

BSOrder_packet:
    pattern:  /orders/packets
    defaults: { _controller: BSOrderBundle:Default:index }

BSOrder_state_open:
    pattern:  /orders/state/open
    defaults: { _controller: BSOrderBundle:Default:state, state: 4 }

BSOrder_state:
    pattern:  /orders/state/{state}
    defaults: { _controller: BSOrderBundle:Default:state, state:5.5 }


BSOrder_set_state:
    pattern:  /orders/setstate/{state}
    defaults: { _controller: BSOrderBundle:Default:setstate, state:6 }


BSOrder_print:
    pattern:  /orders/print
    defaults: { _controller: BSOrderBundle:Default:print }

BSOrder_export:
    pattern:  /orders/export
    defaults: { _controller: BSOrderBundle:Default:export }

BSOrder_accounting:
    pattern:  /orders/accounting/{page}
    defaults: { _controller: BSOrderBundle:Default:accounting,page: 1 }


