
BSOrder_menu:
    pattern:  /orders
    defaults: { _controller: BSOrderBundle:Order:index }


BSOrder_search:
    pattern:  /orders/search
    defaults: { _controller: BSOrderBundle:Order:index }

BSOrder_getInvoice:
    pattern:  /orders/invoice/{orderID}
    defaults: { _controller: BSOrderBundle:Order:getInvoice }

BSOrder_packet:
    pattern:  /orders/packets
    defaults: { _controller: BSOrderBundle:Order:index }

BSOrder_state_open:
    pattern:  /orders/state/open
    defaults: { _controller: BSOrderBundle:Order:state, state: 4 }

BSOrder_state:
    pattern:  /orders/state/{state}
    defaults: { _controller: BSOrderBundle:Order:state, state:5.5 }

BSOrder_sync:
    pattern:  /orders/sync/{state}
    defaults: { _controller: BSOrderBundle:Order:sync, state:7 }


BSOrder_set_state:
    pattern:  /orders/setstate/{state}
    defaults: { _controller: BSOrderBundle:Order:setstate, state:6 }


BSOrder_print:
    pattern:  /orders/print
    defaults: { _controller: BSOrderBundle:Order:print }

BSOrder_export:
    pattern:  /orders/export/{date}
    defaults: { _controller: BSOrderBundle:Order:export, date: 1 }

BSOrder_open:
    pattern:  /orders/open
    defaults: { _controller: BSOrderBundle:Order:open }

BSOrder_accounting:
    pattern:  /orders/accounting/{page}
    defaults: { _controller: BSOrderBundle:Order:accounting,page: 1 }

BSOrder_exported:
    pattern:  /orders/exported/{date}/{page}
    defaults: { _controller: BSOrderBundle:Order:exported,page: 1 }

BSOrder_check:
    pattern:  /orders/check
    defaults: { _controller: BSOrderBundle:Order:check }

