


BSLable_print:
    pattern:  /print
    defaults: { _controller: BSLableBundle:Lable:print }

BSLable_search:
    pattern:  /search
    defaults: { _controller: BSLableBundle:Lable:search }

BSLable_autofill:
    pattern:  /autofill/{search}
    defaults: { _controller: BSLableBundle:Lable:autofill }

BSLable_home:
    pattern:  /{page}
    defaults: { _controller: BSLableBundle:Lable:index,page: 1 }
